### ISSUE TITLE
Is one-shot learning possible?

### ISSUE THREAD

**Issue by HyeonHo99** [RQ-Wu/LAMP#10]
Great Work!

I have a question about the setting. Is LAMP suitable for only few-shot learning or it is also suitable for one-shot learning?
In other words, does LAMP require 8~16 videos always or is one video okay too?

Thank you in advance.

**Comment by RQ-Wu** [comment]
> Great Work!
> 
> I have a question about the setting. Is LAMP suitable for only few-shot learning or it is also suitable for one-shot learning? In other words, does LAMP require 8~16 videos always or is one video okay too?
> 
> Thank you in advance.

Hi~The code of video editing (one-shot learning) is released! Sorry for my late update!

**Comment by HyeonHo99** [comment]
Thank you for the reply and the release !
Wish you best luck for the CVPR 2024 :)
