### ISSUE TITLE
Question about the training time

### ISSUE THREAD

**Issue by CHNxindong** [RQ-Wu/LAMP#12]
Thanks for your great work! I have a question about the training time: when I train the horse_running in my GPU (RTX 3090 24G), it displays about 14hours for training. I want to know wheather this is normal?
![image](https://github.com/RQ-Wu/LAMP/assets/20262070/96fc8592-f463-4c4b-adbb-6df75bce2375)
Expecting your reply!

**Comment by RQ-Wu** [comment]
> Thanks for your great work! I have a question about the training time: when I train the horse_running in my GPU (RTX 3090 24G), it displays about 14hours for training. I want to know wheather this is normal? ![image](https://user-images.githubusercontent.com/20262070/283147064-96fc8592-f463-4c4b-adbb-6df75bce2375.png) Expecting your reply!

This is normal, you can increase the intervals of validation to shorten the training time, usually 10k-20k steps will perform well (depending on the difficulty of the motion)

**Comment by CHNxindong** [comment]
I see. Thanks for your quick reply!
