### ISSUE TITLE
does each model only contain an individual motion or can multiple types of motion be trained inside a single model?

### ISSUE THREAD

**Issue by TruthSearcher** [RQ-Wu/LAMP#2]
does each model only contain an individual motion or can you train multiple types of motion inside a single model like [motiondirector](https://showlab.github.io/MotionDirector/) ?

**Comment by RQ-Wu** [comment]
Each model contains one motion pattern, such as the "horse run" model can generate a horse running with diverse poses, scenes, and styles. Actually, Motiondirector did the same thing as our work (It can not train multiple motions inside a single model, as I know). We are co-current works (around a 5-day gap for paper release). The difference is that Motiondirector tunes a T2V-LDM for a better specific-motion generation, while we tune a T2I-LDM to make it transfer to the video domain with a specific motion pattern.
