### ISSUE TITLE
plans for Google Drive?

### ISSUE THREAD

**Issue by xnmt9** [RQ-Wu/LAMP#4]
Hi there - amazing work! Just wondering when you are planning to upload the models to google drive - excited to play with them

**Comment by RQ-Wu** [comment]
We plan to release the Google Driver link this week. We are trying to solve issues about storage space and uploading speed. Hope you can give us a STAR and stay tuned to our project!

**Comment by RQ-Wu** [comment]
> Hi there - amazing work! Just wondering when you are planning to upload the models to google drive - excited to play with them

https://drive.google.com/drive/folders/1e409tML98gwouIOxFwcFuGVBSNwsfEtY?usp=share_link
Here is our google driver link
